import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { MonthlySnapshot, DeliveryItem } from '@/types/database';
import type { ScopeCalculation } from '@/lib/scope-utils';

const COLORS = {
  primary: '#E3175E',
  success: '#1A9E6A',
  warning: '#F59E0B',
  danger: '#EF4444',
  text: '#1a1a1a',
  muted: '#6B7280',
  border: '#e5e7eb',
  background: '#f9fafb',
};

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: 'Helvetica', color: COLORS.text },
  header: {
    marginBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
    borderBottomStyle: 'solid',
    paddingBottom: 16,
  },
  title: { fontSize: 20, fontWeight: 'bold', color: COLORS.primary, fontFamily: 'Helvetica-Bold' },
  subtitle: { fontSize: 11, color: COLORS.muted, marginTop: 4 },
  brand: { fontSize: 9, color: COLORS.muted, marginTop: 2 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: COLORS.primary,
    marginBottom: 8,
    marginTop: 20,
    fontFamily: 'Helvetica-Bold',
  },
  text: { fontSize: 10, lineHeight: 1.5, color: COLORS.text },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    borderBottomStyle: 'solid',
    paddingVertical: 6,
  },
  cell: { fontSize: 9, flex: 1 },
  cellBold: { fontSize: 9, flex: 1, fontFamily: 'Helvetica-Bold' },
  cellDate: { fontSize: 9, flex: 0.4 },
  cellDateBold: { fontSize: 9, flex: 0.4, fontFamily: 'Helvetica-Bold' },
  cellStatus: { fontSize: 9, flex: 0.4, textAlign: 'right' },
  cellStatusBold: { fontSize: 9, flex: 0.4, textAlign: 'right', fontFamily: 'Helvetica-Bold' },
  scopeBox: {
    backgroundColor: COLORS.background,
    borderRadius: 4,
    padding: 12,
    marginTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scopeBarTrack: {
    height: 8,
    backgroundColor: COLORS.border,
    borderRadius: 4,
    marginTop: 10,
    marginBottom: 4,
  },
  scopeStat: { alignItems: 'center' },
  scopeValue: { fontSize: 16, fontWeight: 'bold', fontFamily: 'Helvetica-Bold' },
  scopeLabel: { fontSize: 8, color: COLORS.muted, marginTop: 2 },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: COLORS.muted,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    borderTopStyle: 'solid',
    paddingTop: 8,
  },
  bulletItem: { flexDirection: 'row', marginBottom: 4 },
  bullet: { width: 12, fontSize: 10 },
  approvalItem: {
    marginBottom: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: '#FEF3C7',
    borderRadius: 4,
  },
});

function formatStatus(status: string): string {
  return status.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

type MonthlyReportPDFProps = {
  clientName: string;
  monthLabel: string;
  snapshot: MonthlySnapshot;
  deliveries: DeliveryItem[];
  scopeCalc: ScopeCalculation | null;
};

export function MonthlyReportPDF({
  clientName,
  monthLabel,
  snapshot,
  deliveries,
  scopeCalc,
}: MonthlyReportPDFProps) {
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const pendingApprovals = deliveries.filter((d) => d.status === 'pending_approval');
  const barWidth = scopeCalc ? `${Math.min(scopeCalc.percentage, 100)}%` : '0%';

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Cover */}
        <View style={styles.header}>
          <Text style={styles.title}>{clientName} — Monthly Report</Text>
          <Text style={styles.subtitle}>{monthLabel}</Text>
          <Text style={styles.brand}>Generated by Luma · {generatedDate}</Text>
        </View>

        {/* Scope Summary */}
        {scopeCalc && (
          <>
            <Text style={styles.sectionTitle}>Scope Summary</Text>
            <View style={styles.scopeBox}>
              <View style={styles.scopeStat}>
                <Text style={styles.scopeValue}>{scopeCalc.totalUsed}</Text>
                <Text style={styles.scopeLabel}>Used</Text>
              </View>
              <View style={styles.scopeStat}>
                <Text style={styles.scopeValue}>{scopeCalc.totalAllocated}</Text>
                <Text style={styles.scopeLabel}>Allocated ({scopeCalc.unitLabel})</Text>
              </View>
              <View style={styles.scopeStat}>
                <Text style={styles.scopeValue}>{scopeCalc.percentage}%</Text>
                <Text style={styles.scopeLabel}>Utilization</Text>
              </View>
              <View style={styles.scopeStat}>
                <Text style={styles.scopeValue}>{scopeCalc.remaining}</Text>
                <Text style={styles.scopeLabel}>Remaining</Text>
              </View>
            </View>
            {/* Visual bar */}
            <View style={styles.scopeBarTrack}>
              <View
                style={{ height: 8, backgroundColor: COLORS.success, borderRadius: 4, width: barWidth }}
              />
            </View>
          </>
        )}

        {/* Deliveries Table */}
        {deliveries.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Deliveries ({deliveries.length})</Text>
            <View style={styles.row}>
              <Text style={styles.cellDateBold}>Date</Text>
              <Text style={styles.cellBold}>Delivery</Text>
              <Text style={{ ...styles.cellBold, flex: 0.5 }}>Category</Text>
              <Text style={styles.cellStatusBold}>Status</Text>
            </View>
            {deliveries.map((d) => (
              <View key={d.id} style={styles.row}>
                <Text style={styles.cellDate}>
                  {(d.completed_at ?? d.created_at)
                    ? new Date(d.completed_at ?? d.created_at).toLocaleDateString('en-US', {
                        month: 'short',
                        day: 'numeric',
                      })
                    : '—'}
                </Text>
                <Text style={styles.cell}>{d.title}</Text>
                <Text style={{ ...styles.cell, flex: 0.5 }}>{d.category}</Text>
                <Text style={styles.cellStatus}>{formatStatus(d.status)}</Text>
              </View>
            ))}
          </>
        )}

        {/* Pending Approvals */}
        {pendingApprovals.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Pending Approvals ({pendingApprovals.length})</Text>
            {pendingApprovals.map((d) => (
              <View key={d.id} style={styles.approvalItem}>
                <Text style={{ ...styles.text, fontFamily: 'Helvetica-Bold' }}>{d.title}</Text>
                {d.category ? (
                  <Text style={{ fontSize: 8, color: COLORS.muted }}>{d.category}</Text>
                ) : null}
              </View>
            ))}
          </>
        )}

        {/* Notes */}
        {snapshot.insights && (
          <>
            <Text style={styles.sectionTitle}>Notes</Text>
            <Text style={styles.text}>{snapshot.insights}</Text>
          </>
        )}

        {/* Wins & Highlights */}
        {snapshot.wins && (
          <>
            <Text style={styles.sectionTitle}>Wins & Highlights</Text>
            <Text style={styles.text}>{snapshot.wins}</Text>
          </>
        )}

        {/* Upcoming Priorities */}
        {snapshot.upcoming_priorities.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Upcoming Priorities</Text>
            {snapshot.upcoming_priorities.map((p) => (
              <View key={p.id} style={styles.bulletItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.text}>
                  {p.text}
                  {p.phase ? ` (${p.phase})` : ''}
                </Text>
              </View>
            ))}
          </>
        )}

        {/* Decisions & Actions */}
        {snapshot.decisions_actions.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Decisions & Actions</Text>
            {snapshot.decisions_actions.map((d) => (
              <View key={d.id} style={styles.bulletItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.text}>
                  {d.text}
                  {d.owner ? ` — ${d.owner}` : ''}
                  {d.due ? ` (due ${d.due})` : ''}
                </Text>
              </View>
            ))}
          </>
        )}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text>Luma • Confidential</Text>
        </View>
      </Page>
    </Document>
  );
}
